---
# Setup Testing Servers.
- hosts: all
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - update_system
    - install_packages
    - disable_firewall
    - disable_selinux
    - setup_ntp
    - create_swap
