---
- name: Install NTP Packages.
  yum:
    name: ['ntp', 'ntpdate']
    state: present

- name: Start NTP.
  service:
    name: ntpd
    state: started

- name: Enable NTP.
  service:
    name: ntpd
    enabled: yes
